version: '3'
services:
  wp:
    image: "anastasiiamiros/my-image"
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_PASSWORD: admin
  mysql:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - "my-datavolume:/var/lib/mysql"
volumes:
  my-datavolume:
